lib/crc32: Fix missing-attribute warnings
This corrects the following compilation errors:

../lib/crc32.c:209:5: warning: 'crc32_le_base' specifies less restrictive attribute than its target 'crc32_le': 'pure' [-Wmissing-attributes]
  209 | u32 crc32_le_base(u32, unsigned char const *, size_t) __alias(crc32_le);
      |     ^~~~~~~~~~~~~
../lib/crc32.c:195:19: note: 'crc32_le_base' target declared here
  195 | u32 __pure __weak crc32_le(u32 crc, unsigned char const *p, size_t len)
      |                   ^~~~~~~~
../lib/crc32.c:210:5: warning: '__crc32c_le_base' specifies less restrictive attribute than its target '__crc32c_le': 'pure' [-Wmissing-attributes]
  210 | u32 __crc32c_le_base(u32, unsigned char const *, size_t) __alias(__crc32c_le);
      |     ^~~~~~~~~~~~~~~~
../lib/crc32.c:200:19: note: '__crc32c_le_base' target declared here
  200 | u32 __pure __weak __crc32c_le(u32 crc, unsigned char const *p, size_t len)
      |                   ^~~~~~~~~~~

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>